version: '3.7'
services:
  db:
    build:
      context: ./docker
      dockerfile: oracle.dockerfile
    restart: unless-stopped # always
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      SOME_VAR: SOME_VALUE
    volumes:
#     - ./docker/oracle/volumes/ORCL:/ORCL Ебаный оракл не смог создать базу в локальной папке
      - ./docker/oracle/volumes/sql:/home/oracle/sql
      - ./docker/oracle/volumes/dump:/home/oracle/dump
volumes:
  oracle-12:
