BEGIN
 delete from PC_ATTRIBUTES where ID> 563;
 delete from PC_ATTR_BY_REGIONS_HIST where ID_COMPANY > 563;
 --delete from PC_ATTR_BY_REGIONS_HIST where ID_COMPANY = 563 AND ID_REGION in (455, 435);  -- TODO: не работает (но и не выбрасывает ошибку)
 delete from PC_ATTR_BY_REGIONS_HIST where ID_COMPANY = 563 AND ID_REGION = 455;
 delete from PC_ATTR_BY_REGIONS_HIST where ID_COMPANY = 563 AND ID_REGION = 435;
 delete from PC_ATTRIBUTES_HIST where ID_COMPANY NOT IN (SELECT ID FROM PC_ATTRIBUTES);
 delete from PC_OFFICES where ID_COMPANY NOT IN (SELECT ID FROM PC_ATTRIBUTES);
 delete from PC_OFFICES where ID_COMPANY = 563 AND ID <> '33709da2-cc2c-4017-a291-bfcf6501c717';
 delete from PC_OFFICES_ADDRESS_HIST where ID_OFFICE NOT IN (SELECT ID FROM PC_OFFICES);
 delete from PRESENCE_LOCALITY where ID_COMPANY NOT IN (SELECT ID FROM PC_ATTRIBUTES) OR ID_OFFICE NOT IN (SELECT ID FROM PC_OFFICES) OR ID_LOCALITY NOT IN (SELECT ID FROM PUB.SHORT_LIST_LOCATIONS WHERE SOVA=1);
 delete from PC_STAFF where ID_COMPANY NOT IN (SELECT ID FROM PC_ATTRIBUTES);
 delete from PC_STAFF where ID_COMPANY IS NULL;
 delete from PC_STAFF where ID_COMPANY = 355 AND FULLNAME = 'Солонникова Мария Михайловна';
 delete from PC_STAFF where FULLNAME = 'ty';
 delete from QUAL_CERT where DIRECTION_ID is null;
END;
