--create USER SOVA IDENTIFIED BY SOVA;
--GRANT CONNECT TO SOVA;
--GRANT CONNECT, RESOURCE, DBA TO  SOVA;
--GRANT CREATE SESSION TO  SOVA;

-- создать пользователя
create USER C##SOVA IDENTIFIED BY SOVA;
GRANT CONNECT TO C##SOVA;
GRANT CONNECT, RESOURCE, DBA TO  C##SOVA;
GRANT CREATE SESSION TO  C##SOVA;

-- создать папку для дампов
CREATE OR REPLACE DIRECTORY test_dir AS '/home/oracle/dump';
GRANT READ, WRITE ON DIRECTORY test_dir TO C##SOVA;
EXIT;
