module.exports = {
    'ID_COMPANY': '№ п/п',
    'FEDERAL_DISTRICT': 'Федеральный округ',
    'STATE': 'Регион (субъект РФ)',
    'LOCALITY': 'Населенный пункт',
    'NAME': 'Наименование оценочной организации',
    'TIN': 'ИНН организации',
    'HEAD': 'ФИО руководителя',
    'OFFICE_ADDRESS': 'Адрес',
    'EMAIL': 'Электронная почта',
    'PHONE': 'Телефон',
    'RES_REALTY_WITH_LAND':'ЖД',
    'RES_REALTY_OTHERS':'ЖН',
    'COMMERCIAL_REALTY':'КН',
    'EQUIPMENT':'ОБ',
    'MOVABLE_PROPERTY':'ДИ',
    'OTHERS':'ПР',
    'CURATOR_NAME':'Куратор',
    'STATUS_ROC':'Статус РОК',
};
